frameworkVersion: ^3.33.0

service: laravel-nuxt

provider:
    name: aws
    region: ap-northeast-1
    profile: default
    stage: dev

custom:
    env: ${file(./config.${opt:stage, self:provider.stage}.yml)}
    apigwBinary:
        types:
            - '*/*'
    customDomain:
        rest:
            domainName: ${self:custom.env.SERVICE_DOMAIN}
            certificateName: ${self:custom.env.SERVICE_DOMAIN}
            stage: ${self:provider.stage}
            basePath: ''
            endpointType: regional
            securityPolicy: tls_1_2
        http:
            domainName: ${self:custom.env.API_DOMAIN}
            certificateName: ${self:custom.env.API_DOMAIN}
            basePath: ''
            endpointType: regional
            securityPolicy: tls_1_2

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!frontend/node_modules/**'

functions:

    web:
        runtime: nodejs18.x
        handler: ./frontend/.output/server/index.handler
        url: true
        events:
            - http:
                path: /
                method: ANY
            - http:
                path: /{proxy+}
                method: ANY
            # - http:
            #     integration: http-proxy
            #     path: /api/{proxy+}
            #     method: ANY
            #     request:
            #         uri: ${self:custom.env.API_DOMAIN}/api/{proxy}
            #         parameters:
            #             paths:
            #                 proxy: true # mark path parameter as required

    # This function runs the Laravel website/API
    api:
        handler: public/index.php
        runtime: php-81-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        environment:
            APP_ENV: ${self:custom.env.APP_ENV}
            APP_KEY: ${self:custom.env.APP_KEY}
            BREF_BINARY_RESPONSES: '1'
        events:
            - httpApi:
                path: /api
                method: ANY
            - httpApi:
                path: /api/{proxy+}
                method: ANY

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-81-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

plugins:
    - ./vendor/bref/bref
    - serverless-apigw-binary
    - serverless-domain-manager # uncomment the plugin
