SERVICE_DOMAIN: bref-sample.okdyy75.com
API_DOMAIN: bref-sample.okdyy75.com
SERVICE_DOMAIN_CERTIFICATE: arn:aws:acm:us-east-1:xxxxxxxxxx:certificate/2becb870-eebb-4cb2-9844-1e2b208968ce
SERVICE_DOMAIN_HOSTED_ZONE_ID: Z0258482MIZ93VL5OUBM

# laravel
APP_ENV: production
APP_KEY: xxxxxxxxxx
