frameworkVersion: ^3.33.0

service: laravel-server

provider:
    name: aws
    region: ap-northeast-1
    stage: dev

custom:
    env: ${file(./config.${opt:stage, self:provider.stage}.yml)}

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-81-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        environment:
            APP_ENV: ${self:custom.env.APP_ENV}
            APP_KEY: ${self:custom.env.APP_KEY}
            BREF_BINARY_RESPONSES: '1'
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-81-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

constructs:
    website:
        type: server-side-website
        domain: ${self:custom.env.SERVICE_DOMAIN}
        certificate: arn:aws:acm:us-east-1:724443887064:certificate/4ccd82f4-2c64-4eaa-9bc5-d833189e356d
        assets:
            '/build/*': public/build
            '/favicon.ico': public/favicon.ico
            '/robots.txt': public/robots.txt

plugins:
  - ./vendor/bref/bref
  - serverless-lift
