frameworkVersion: ^3.33.0

service: laravel-react

provider:
    name: aws
    region: ap-northeast-1
    profile: default
    stage: dev

custom:
    env: ${file(./config.${opt:stage, self:provider.stage}.yml)}

package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!.env'

functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-81-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        environment:
            APP_ENV: ${self:custom.env.APP_ENV}
            APP_KEY: ${self:custom.env.APP_KEY}
            BREF_BINARY_RESPONSES: '1'
        events:
            - httpApi: '*'

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-81-console
        timeout: 720 # in seconds
        # Uncomment to also run the scheduler every minute
        #events:
        #    - schedule:
        #          rate: rate(1 minute)
        #          input: '"schedule:run"'

constructs:
    website:
        type: server-side-website
        domain: ${self:custom.env.SERVICE_DOMAIN}
        certificate: ${self:custom.env.SERVICE_DOMAIN_CERTIFICATE}
        assets:
            '/build/*': public/build
            '/favicon.ico': public/favicon.ico
            '/robots.txt': public/robots.txt

plugins:
    - ./vendor/bref/bref
    - serverless-lift

resources:
    Resources:
        Route53Record:
            Type: AWS::Route53::RecordSet
            Properties:
                HostedZoneId: ${self:custom.env.SERVICE_DOMAIN_HOSTED_ZONE_ID}
                Name: ${self:custom.env.SERVICE_DOMAIN}
                Type: A
                AliasTarget:
                    HostedZoneId: Z2FDTNDATAQYW2 # Cloudfront Route53 HostedZoneId. This does not change.
                    DNSName: ${construct:website.cname}
